#!/usr/bin/env bash
# write one menu entry per live install found in the wine prefix (editions and
# majors can coexist), each pinned via ABLETON_LIVE_EXE so the launcher never
# has to guess. icons come out of the exe itself: winemenubuilder is disabled
# in this stack, so nothing else extracts them. safe to rerun; only files
# carrying the generated marker are ever overwritten
set -euo pipefail

export PATH="@toolPath@:$PATH"
WINEPREFIX="${ABLETON_WINEPREFIX:-$HOME/.wine-ableton}"
apps="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
icons="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor"

shopt -s nullglob
exes=("$WINEPREFIX"/drive_c/ProgramData/Ableton/*/Program/"Ableton Live"*.exe)
if [ ${#exes[@]} -eq 0 ]; then
    echo "no Live installs found in $WINEPREFIX (run ableton-live-setup first)" >&2
    exit 1
fi

mkdir -p "$apps"
for exe in "${exes[@]}"; do
    base="$(basename "$exe" .exe)"                      # Ableton Live 12 Suite
    slug="$(tr '[:upper:] ' '[:lower:]-' <<<"$base")"   # ableton-live-12-suite

    # pull the embedded icon group and install every size hicolor-style;
    # depths sort ascending in the glob so the 32-bit cut wins per size
    tmp="$(mktemp -d)"
    if wrestool -x --type=14 -o "$tmp" "$exe" 2>/dev/null; then
        for ico in "$tmp"/*.ico; do
            icotool -x -o "$tmp" "$ico" 2>/dev/null || true
        done
        for png in "$tmp"/*.png; do
            s="$(sed -n 's/.*_\([0-9]*\)x[0-9]*x[0-9]*\.png$/\1/p' <<<"$png")"
            [ -n "$s" ] || continue
            install -Dm644 "$png" "$icons/${s}x${s}/apps/$slug.png"
        done
    fi
    rm -rf "$tmp"

    entry="$apps/$slug.desktop"
    if [ -e "$entry" ] && ! grep -q '^X-AbletonWine-Generated=true' "$entry"; then
        echo "   keeping $entry (not generated by this tool)"
        continue
    fi
    cat > "$entry" <<EOF
[Desktop Entry]
Type=Application
Name=$base
Comment=Music production (Wine, patched d2d1-dcomp stack)
Exec=env "ABLETON_LIVE_EXE=$exe" @launcher@
Icon=$slug
StartupNotify=true
StartupWMClass=${base,,}.exe
Categories=AudioVideo;Audio;
X-AbletonWine-Generated=true
EOF
    echo "   wrote $entry"
done
update-desktop-database "$apps" 2>/dev/null || true
